# 新建数据库
DROP DATABASE IF EXISTS szdt;
CREATE DATABASE szdt CHARACTER SET UTF8;

use szdt;
set character_set_server = utf8;

# ITEM
DROP TABLE IF EXISTS `SZDT_ITEM`;
CREATE TABLE `SZDT_ITEM`
(
    `ID`                integer             NOT NULL        AUTO_INCREMENT,
    `NAME`              varchar(32)         NOT NULL        COMMENT '预约项目名称',
    `COUNT`             integer             NOT NULL        COMMENT '最大预约数量',
    `CATEGORY`          integer             NOT NULL        COMMENT '预约项目类别 0-器械 1-跑步机 2-乒乓球 3-美式台球 4-英式台球 5-瑜伽',
    CONSTRAINT PK_SZDT_ITEM PRIMARY KEY (`ID`)
)
;

# INTERVAL
DROP TABLE IF EXISTS `SZDT_INTERVAL`;
CREATE TABLE `SZDT_INTERVAL`
(
    `ID`                integer             NOT NULL        AUTO_INCREMENT,
    `START_TIME`        varchar(16)         NOT NULL        COMMENT '预约开始时间',
    `END_TIME`          varchar(16)         NOT NULL        COMMENT '预约结束时间',
    `DATE_TYPE`         integer             NOT NULL        COMMENT '日期类别 0-工作日 1-休息日',
    `CATEGORY`          integer             NOT NULL        COMMENT '预约类别',
    CONSTRAINT PK_SZDT_INTERVAL PRIMARY KEY (`ID`)
)
;
# BOOKING
DROP TABLE IF EXISTS `SZDT_BOOKING`;
CREATE TABLE `SZDT_BOOKING`
(
    `ID`                integer             NOT NULL        AUTO_INCREMENT,
    `ITEM_ID`           integer             NOT NULL        COMMENT '预约项目',
    `INTERVAL_ID`       integer             NOT NULL        COMMENT '预约时段',
    `BOOKING_DATE`      date                                COMMENT '预约日期',
    `USERNAME`          varchar(64)                         COMMENT '预约人',
    CONSTRAINT PK_SZDT_BOOKING PRIMARY KEY (`ID`)
)
;

INSERT INTO SZDT_ITEM (NAME, COUNT, CATEGORY) VALUES ('器械', 4, 0);
INSERT INTO SZDT_ITEM (NAME, COUNT, CATEGORY) VALUES ('跑步机1号', 1, 1);
INSERT INTO SZDT_ITEM (NAME, COUNT, CATEGORY) VALUES ('跑步机2号', 1, 1);
INSERT INTO SZDT_ITEM (NAME, COUNT, CATEGORY) VALUES ('跑步机3号', 1, 1);
INSERT INTO SZDT_ITEM (NAME, COUNT, CATEGORY) VALUES ('跑步机4号', 1, 1);

INSERT INTO SZDT_ITEM (NAME, COUNT, CATEGORY) VALUES ('1号', 1, 2);
INSERT INTO SZDT_ITEM (NAME, COUNT, CATEGORY) VALUES ('2号', 1, 2);

INSERT INTO SZDT_ITEM (NAME, COUNT, CATEGORY) VALUES ('美式台球', 1, 3);
INSERT INTO SZDT_ITEM (NAME, COUNT, CATEGORY) VALUES ('英式台球', 1, 4);

INSERT INTO SZDT_ITEM (NAME, COUNT, CATEGORY) VALUES ('舞蹈场地', 20, 5);

INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:00', '13:00', 0, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:00', '14:00', 0, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:00', '18:00', 0, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:00', '19:00', 0, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:00', '20:00', 0, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:00', '21:00', 0, 0);

INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('09:30', '10:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('10:30', '11:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('11:30', '12:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:30', '13:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:30', '14:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('14:30', '15:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('15:30', '16:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('16:30', '17:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:30', '18:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:30', '19:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:30', '20:30', 1, 0);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:30', '21:00', 1, 0);


INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:00', '12:30', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:30', '13:00', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:00', '13:30', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:30', '14:00', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:00', '17:30', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:30', '18:00', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:00', '18:30', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:30', '19:00', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:00', '19:30', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:30', '20:00', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:00', '20:30', 0, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:30', '21:00', 0, 1);

INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('09:30', '10:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('10:00', '10:30', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('10:30', '11:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('11:00', '11:30', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('11:30', '12:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:00', '12:30', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:30', '13:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:00', '13:30', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:30', '14:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('14:00', '14:30', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('14:30', '15:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('15:00', '15:30', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('15:30', '16:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('16:00', '16:30', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('16:30', '17:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:30', '18:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:00', '18:30', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:30', '19:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:00', '19:30', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:30', '20:00', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:00', '20:30', 1, 1);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:30', '21:00', 1, 1);


INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:00', '13:00', 0, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:00', '14:00', 0, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:00', '18:00', 0, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:00', '19:00', 0, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:00', '20:00', 0, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:00', '21:00', 0, 2);

INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('09:30', '10:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('10:30', '11:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('11:30', '12:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:30', '13:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:30', '14:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('14:30', '15:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('15:30', '16:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('16:30', '17:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:30', '18:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:30', '19:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:30', '20:30', 1, 2);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:30', '21:00', 1, 2);


INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:00', '12:30', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:30', '13:00', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:00', '13:30', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:30', '14:00', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:00', '17:30', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:30', '18:00', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:00', '18:30', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:30', '19:00', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:00', '19:30', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:30', '20:00', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:00', '20:30', 0, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:30', '21:00', 0, 3);

INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('09:30', '10:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('10:00', '10:30', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('10:30', '11:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('11:00', '11:30', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('11:30', '12:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:00', '12:30', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:30', '13:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:00', '13:30', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:30', '14:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('14:00', '14:30', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('14:30', '15:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('15:00', '15:30', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('15:30', '16:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('16:00', '16:30', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('16:30', '17:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:30', '18:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:00', '18:30', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:30', '19:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:00', '19:30', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:30', '20:00', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:00', '20:30', 1, 3);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:30', '21:00', 1, 3);

INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:00', '12:30', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:30', '13:00', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:00', '13:30', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:30', '14:00', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:00', '17:30', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:30', '18:00', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:00', '18:30', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:30', '19:00', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:00', '19:30', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:30', '20:00', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:00', '20:30', 0, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:30', '21:00', 0, 4);

INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('09:30', '10:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('10:00', '10:30', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('10:30', '11:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('11:00', '11:30', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('11:30', '12:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:00', '12:30', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:30', '13:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:00', '13:30', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:30', '14:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('14:00', '14:30', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('14:30', '15:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('15:00', '15:30', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('15:30', '16:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('16:00', '16:30', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('16:30', '17:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:30', '18:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:00', '18:30', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:30', '19:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:00', '19:30', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:30', '20:00', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:00', '20:30', 1, 4);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:30', '21:00', 1, 4);

INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:00', '13:00', 0, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:00', '14:00', 0, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:00', '18:00', 0, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:00', '19:00', 0, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:00', '20:00', 0, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:00', '21:00', 0, 5);

INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('09:30', '10:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('10:30', '11:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('11:30', '12:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('12:30', '13:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('13:30', '14:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('14:30', '15:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('15:30', '16:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('16:30', '17:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('17:30', '18:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('18:30', '19:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('19:30', '20:30', 1, 5);
INSERT INTO SZDT_INTERVAL(START_TIME, END_TIME, DATE_TYPE, CATEGORY) VALUES ('20:30', '21:00', 1, 5);
COMMIT;